server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Soporte para el dominio oficial
    location /cbd_monitor/ {
        try_files $uri $uri/ /cbd_monitor/index.html;
    }

    # Soporte para la IP
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend
    location /cbd_monitor/api/ {
        proxy_pass http://cbd-monitor-backend:5000/;
    }

    location /api/ {
        proxy_pass http://cbd-monitor-backend:5000/;
    }
}