server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # AGREGAR ESTO PARA GOOGLE OAUTH
    # COMENTADO PARA EVITAR BLOQUEOS DE POPUPS (GOOGLE OAUTH, CHATBOT)
    # add_header Cross-Origin-Opener-Policy "same-origin-allow-popups";

    location / {
        try_files $uri $uri/ /cbd_monitor/index.html /index.html;
    }

    location /cbd_monitor/ {
        alias /usr/share/nginx/html/cbd_monitor/;
        try_files $uri $uri/ /cbd_monitor/index.html;
    }

    # Proxies para el API
    location /api/ {
        proxy_pass http://cbd-monitor-backend:5000/;
    }

    location /cbd_monitor/api/ {
        proxy_pass http://cbd-monitor-backend:5000/;
    }
}