server {
    listen 80;

    # Directorio raíz donde están los archivos de React
    root /usr/share/nginx/html;
    index index.html;

    # 1. Soporte para la IP (http://172.16.222.222:8080/)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Soporte para el dominio (https://sistemas.mopc.gov.py/cbd_monitor)
    location /cbd_monitor {
        # Si entran sin la barra final, la agregamos
        rewrite ^/cbd_monitor$ /cbd_monitor/ permanent;
        
        # Eliminamos el prefijo /cbd_monitor/ para buscar el archivo real en el disco
        rewrite ^/cbd_monitor/(.*)$ /$1 break;
        
        try_files $uri $uri/ /index.html;
    }

    # 3. Proxies para el API
    location /api/ {
        proxy_pass http://cbd-monitor-backend:5000/;
        proxy_set_header Host $host;
    }

    location /cbd_monitor/api/ {
        proxy_pass http://cbd-monitor-backend:5000/;
        proxy_set_header Host $host;
    }
}